/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsIndexImport } from './routes/projects_/index'
import { Route as AuthResetpasswordImport } from './routes/auth/resetpassword'
import { Route as AuthEmailconfirmImport } from './routes/auth/emailconfirm'
import { Route as ProjectsProjectIdIndexImport } from './routes/projects_/$projectId/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIndexRoute = ProjectsIndexImport.update({
  id: '/projects_/',
  path: '/projects/',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetpasswordRoute = AuthResetpasswordImport.update({
  id: '/auth/resetpassword',
  path: '/auth/resetpassword',
  getParentRoute: () => rootRoute,
} as any)

const AuthEmailconfirmRoute = AuthEmailconfirmImport.update({
  id: '/auth/emailconfirm',
  path: '/auth/emailconfirm',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexImport.update({
  id: '/projects_/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/emailconfirm': {
      id: '/auth/emailconfirm'
      path: '/auth/emailconfirm'
      fullPath: '/auth/emailconfirm'
      preLoaderRoute: typeof AuthEmailconfirmImport
      parentRoute: typeof rootRoute
    }
    '/auth/resetpassword': {
      id: '/auth/resetpassword'
      path: '/auth/resetpassword'
      fullPath: '/auth/resetpassword'
      preLoaderRoute: typeof AuthResetpasswordImport
      parentRoute: typeof rootRoute
    }
    '/projects_/': {
      id: '/projects_/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects_/$projectId/': {
      id: '/projects_/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/emailconfirm': typeof AuthEmailconfirmRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/emailconfirm': typeof AuthEmailconfirmRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/emailconfirm': typeof AuthEmailconfirmRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/projects_/': typeof ProjectsIndexRoute
  '/projects_/$projectId/': typeof ProjectsProjectIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/emailconfirm'
    | '/auth/resetpassword'
    | '/projects'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/emailconfirm'
    | '/auth/resetpassword'
    | '/projects'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/auth/emailconfirm'
    | '/auth/resetpassword'
    | '/projects_/'
    | '/projects_/$projectId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthEmailconfirmRoute: typeof AuthEmailconfirmRoute
  AuthResetpasswordRoute: typeof AuthResetpasswordRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthEmailconfirmRoute: AuthEmailconfirmRoute,
  AuthResetpasswordRoute: AuthResetpasswordRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/emailconfirm",
        "/auth/resetpassword",
        "/projects_/",
        "/projects_/$projectId/"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/auth/emailconfirm": {
      "filePath": "auth/emailconfirm.ts"
    },
    "/auth/resetpassword": {
      "filePath": "auth/resetpassword.ts"
    },
    "/projects_/": {
      "filePath": "projects_/index.tsx"
    },
    "/projects_/$projectId/": {
      "filePath": "projects_/$projectId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
